### ISSUE TITLE
Request: Make cronnext's output be YAML

### ISSUE THREAD

**Issue by petdance** [cronie-crond/cronie#190]
I'd like to process the output of cronnext using tools like `yq`. The output that cronnext gives is mostly YAML-like, but not entirely so.

This crontab line:

```
15 17 * * * echo "Out of my brain on the train" > /tmp/foo.log
```

gets printed by cronnext as:

```
next: 1726006500
nextjobs:
  - user: alester
    cmd: "echo "Out of my brain on the train" > /tmp/foo.log"
    flags: 0x0C
    flagnames: DOM_STAR|DOW_STAR
    delay: 0
    next: 1726006500
    nextstring: Tue Sep 10 17:15:00 2024
```

but a tool like `yq` can't parse that because the double quotes in the cmd: value aren't escaped. It would be fine if it was:

``` yaml
next: 1726006500
nextjobs:
  - user: alester
    cmd: "echo \"Out of my brain on the train\" > /tmp/foo.log"
    flags: 0x0C
    flagnames: DOM_STAR|DOW_STAR
    delay: 0
    next: 1726006500
    nextstring: Tue Sep 10 17:15:00 2024
```

I understand that nowhere does `cronnext` say that its output is YAML, and it would be great if it could be made so.  If you didn't want to change the output because existing tools that use the output could break, an optional `--yaml` option to make the strict YAML format output would work, too.

I don't know what other things might have to change in the output to be correct YAML. I know there are a bunch of special characters and sequences that need to be escaped, but I don't know the full list. I figure there are plenty of libraries out there to do the dirty work.
