### ISSUE TITLE
Wrongly handles schedules with day-of-monts and day-of-weeks

### ISSUE THREAD

**Issue by pastakhov** [cronie-crond/cronie#191]
```
# cat cronta              
0 11 1-7 * FRI echo test
```
```
# cronnext -l cronta 
next: 1728644400
nextjobs:
  - user: cronta
    cmd: "echo test"
    flags: 0x00
    flagnames:
    delay: 0
    next: 1728644400
    nextstring: Fri Oct 11 11:00:00 2024
```

It should be Fri Nov 1 11:00:00 2024
